{
    "name": "Education Admission",
    "summary": """Education Admission""",
    "category": "Crm",
    "version": "1.1.1",
    "sequence": 1,
    "depends": ['base', 'web', 'crm', 'stock', 'account', 'contacts', 'base', 'crm_lead_cust', 'crm_lead_customisation',
                'mail'],
    "data": [
        'security/security.xml',
        'security/record_rules.xml',
        # 'security/batch_record_rules.xml',
        # 'security/class_record.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        'wizard/mobile.xml',
        'wizard/due_wizard.xml',
        'wizard/conversion.xml',
        'wizard/allocaton.xml',
        'wizard/reallocation.xml',
        'views/addmission.xml',
        'views/batchmaster.xml',
        'views/partner.xml',
        'views/due.xml',
        'views/crm_logic.xml',
        'views/inherit.xml',
        'views/class_room.xml',
        'views/payment_notes.xml',
        'report/report.xml',
        'report/admission_template.xml',
    ],
    "demo": [],
    "application": True,
    "installable": True,
    "auto_install": False,
}
